---
title: "00_setup_environemnt"
author: "Puvvula"
date: "2023-06-09"
output: pdf_document
---

#installing packages
```{r}
install_packages <- function(package_list) {
  # Check if package_list is a character vector
  if (!is.character(package_list)) {
    stop("Package list must be a character vector.")
  }

  # Install packages and their dependencies
  for (package in package_list) {
    if (!require(package, character.only = TRUE, quietly = TRUE)) {
      install.packages(package, dependencies = TRUE)
    } else {
      cat(paste(package, "is already installed. Skipping installation.\n"))
    }
  }
  
  # Load the installed packages
  invisible(lapply(package_list, library, character.only = TRUE))
}

```

#list packages - general r 
```{r}
install_packages(c("tidyverse", "janitor", "haven", "reshape2", "pacman", "skimr",
                 "readr", "kableExtra", "gridExtra", "stringr", "fitdistrplus",
                 "RJSONIO"))
```

#tinytex for rmd files
```{r}
install.packages('tinytex')
tinytex::install_tinytex()
```

#metaboanalyst setup
```{r}
metanr_packages <- function(){
metr_pkgs <- c("impute", "pcaMethods", "globaltest", "GlobalAncova", "Rgraphviz", "preprocessCore", "genefilter", "SSPA", "sva", "limma", "KEGGgraph", "siggenes","BiocParallel", "MSnbase", "multtest", "RBGL", "edgeR", "fgsea", "devtools", "crmn")
list_installed <- installed.packages()
new_pkgs <- subset(metr_pkgs, !(metr_pkgs %in% list_installed[, "Package"]))
if(length(new_pkgs)!=0){if (!requireNamespace("BiocManager", quietly = TRUE))
        install.packages("BiocManager")
        BiocManager::install(new_pkgs)
        print(c(new_pkgs, " packages added..."))
    }

if((length(new_pkgs)<1)){
        print("No new packages added...")
    }
}


metanr_packages()

#####################
# Step 1: Install devtools
install.packages("devtools")
library(devtools)

# Step 2: Install MetaboAnalystR without documentation
devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)

# Step 2: Install MetaboAnalystR with documentation
devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = TRUE, build_manual =T)

```

